{% set name = "google-cloud-bigquery-datatransfer" %}
{% set version = "3.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fdc8cb68a3ee54780f673f06b3cce83a5bb5d600db7ad363c85e38bf45afb59c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - google-api-core-grpc >=1.28.0,<3.0.0dev
    - packaging >=14.3
    - pytz >=2021.1

test:
  imports:
    - google.cloud.bigquery_datatransfer
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/googleapis/python-bigquery-datatransfer
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: BigQuery Data Transfer API client library
  description: "BigQuery Data Transfer API is a Google Cloud service that lets client applications transfer data from partner SaaS applications to Google BigQuery on a scheduled, managed basis.\nSee the [quick start guide](https://googleapis.dev/python/bigquerydatatransfer/latest/index.html#quick-start)."

  doc_url: https://googleapis.dev/python/bigquerydatatransfer/latest/index.html
  dev_url: https://github.com/googleapis/python-bigquery-datatransfer

extra:
  recipe-maintainers:
    - parthea
    - xylar
